Yelee: "3.5"

menu:
  主页: /
  所有文章: /archives
  标签云: /tags
  关于我: /1900/01/01/ge-ren-jian-li/

show_more: 查看更多  

avatar: /imgs/coder.jpg
favicon: /imgs/coder.jpg

since: 2012

subnav:
  Email: "mailto:&#115;&#117;&#110;&#104;&#97;&#111;&#48;&#53;&#53;&#48;&#64;&#49;&#54;&#51;&#46;&#99;&#111;&#109;"
  GitHub: "https://github.com/sunhao-java"
  RSS: "/atom.xml"
  简书: "https://www.jianshu.com/u/9a33a20b0343"
  知乎: "https://www.zhihu.com/people/crazy_coder"

background_image: 0
base_font_size: 16

color_scheme: yilia

highlight_style:
  on: true
  inline_code: 3
  code_block: 4

blockquote_style:
  on: true
  blockquote: 3

heading_style: 2

list_style: 1

left_col_width: 300

copyright: true

toc:
  on: true
  list_number: true
  max_depth: 3
  nowrap: false

animate: true
jquery_ui: true

limit_article_width: 
  on: false
  max_width: 60

tagcloud: true

friends:
  GitHub: https://github.com/sunhao-java
  Git@OSC: https://gitee.com/crazy-coder
  开源中国: https://my.oschina.net/sunhaojava
  路路同学的博客: https://broucetrong.github.io/

aboutme: Talk is cheap,show me the code.

open_in_new:
  global: 0
  title: false
  post: true
  tags: false
  categories: false
  article_nav: false
  archives: true
  mini_archives: true
  menu: false
  friends: true
  socail: true

rss: /atom.xml

ie_updater:
  on: true
  link: //outdatedbrowser.com/

tab_title_change: 
  on: false
  left_tab_title: '(つェ⊂) 我藏好了哦~ '
  return_tab_title: '(*´∇｀*) 被你发现啦~ '

search: 
  on: true
  onload: true

fancybox: true
mathjax: true

share: 
  on: true
  baidu: true
  addthis: false
  addthis_pubid: "ra-56ff76c972fc0cf9"

baidu_site: 
google_site: 

google_analytics: UA-75096622-1

baidu_tongji: 

visit_counter:
  on: false
  site_visit: true
  page_visit: true

github_widget: true

progressBar:
  on: true
  type: "minimal"
  color: blue

CDN:
  jquery: //cdn.bootcss.com/jquery/2.2.4/jquery.min.js
  require: //cdn.bootcss.com/require.js/2.2.0/require.min.js
  fontawesome: //cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css
  fancybox_js: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.js
  fancybox_css: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css
  animate_css: //cdn.bootcss.com/animate.css/3.5.1/animate.min.css
  jquery_ui_js: //cdn.bootcss.com/jqueryui/1.10.4/jquery-ui.min.js
  jquery_ui_css: //cdn.bootcss.com/jqueryui/1.10.4/css/jquery-ui.min.css
  pace_js: //cdn.bootcss.com/pace/1.0.2/pace.min.js
  clipboard: //cdn.bootcss.com/clipboard.js/1.5.10/clipboard.min.js
  mathjax: //cdn.bootcss.com/mathjax/2.6.1/MathJax.js
  scrollreveal: //cdn.bootcss.com/scrollReveal.js/3.1.4/scrollreveal.min.js